# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  hydra:
    image: hydra
    container_name: hydra-video
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - C:\home\data\tmp\sql:/app/storage/sql
      - C:\home\data\tmp\files:/app/storage/files
